#Site settings
title: Arcadia
email: gianluca@gianlucacosta.info
description: Dreams and poetry
baseurl: "/Arcadia"
url: "http://gianlucacosta.info"
twitter_username: giancosta86
github_username:  giancosta86

# Build settings
markdown: kramdown

permalink: /:title

webrick:
  headers:
    Access-Control-Allow-Origin: '*'
