#Site settings
title: Arcadia

email: gianluca@gianlucacosta.info

description: Dreams and poetry

baseurl: "/Arcadia"
url: "http://gianlucacosta.info"

# Build settings
markdown: kramdown

permalink: /:title
