name: Publish website

on:
  pull_request:
    types: closed
    branches: main

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/publish-github-pages@v8

      - uses: giancosta86/aurora-github/actions/tag-and-release@v8
