name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-website:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/publish-github-pages@v10

  tag-and-release:
    runs-on: ubuntu-24.04
    needs: publish-website
    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/tag-and-release@v10
        with:
          git-strategy: squash
