name: Verify source code

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/inject-branch-version@v4.0.0

      - uses: giancosta86/aurora-github/actions/verify-npm-package@v4.0.0
        with:
          enforce-esm: false
